### PR TITLE
RHMAP-7288 - updated fh-mbaas-api version

### PR DESCRIPTION
**Pull request by odra**

### CODE REVIEW

**Comment by matzew** [comment]
@david-martin @maleck13 what's usually done for testing ?

**Comment by david-martin** [comment]
@matzew I'm not familiar with how to test  this app. It might be good to put together a happy path that exercises the /push endpoint?

**Comment by matzew** [comment]
Doing some verifications now

**Comment by matzew** [comment]
* created a project using push starter and did setup push
* updated the cloud app, pointing to the PR branch
* (re)deployed on Node0.10
* did invoke the /push endpoint of the cloud app

**RESULT**
* JSON response from the /push endpoint:
```
{
  "msg": "Message to internal Push server delivered for further processing!"
}
```
* go to the push enabled variant: notice one more push sent....

**Pull request merged**
