### PR TITLE
RHMAP-4875 Update fh-mbaas-api version with fh.db changes for shared …

### PR DESCRIPTION
**Pull request by matzew**
…mongo in mbaas

### CODE REVIEW

**Comment by matzew** [comment]
@david-martin @jasonmadigan I added this template yesterday, for a different fix.

I feel like we should update the API here too :)

**Comment by david-martin** [comment]
@matzew Is this template in use in fh-template-apps?
Wondering why the 'fh templates' cmd didn't pick up on this template

**Comment by matzew** [comment]
not yet.
I haz a PR for that: https://github.com/feedhenry/fh-template-apps/pull/133

On Tue, Mar 8, 2016 at 3:52 PM, David Martin <notifications@github.com>
wrote:

> @matzew <https://github.com/matzew> Is this template in use in
> fh-template-apps?
> Wondering why the 'fh templates' cmd didn't pick up on this template
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/feedhenry-templates/hello-push-cloud/pull/1#issuecomment-193812560>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by jasonmadigan** [comment]
weird - wonder why this wasn't picked up and updated at the same time as the rest of the cloud templates. anyway, change looks ok, but I think we found an issue with `fh-mbaas-api` 5.9.0

Give @nialldonnellyfh a shout about 5.9.1 - should use this instead

**Comment by david-martin** [comment]
Will bump to 5.9.1 as part of different work to update all templates

**Comment by jasonmadigan** [comment]
thanks @david-martin!

**Pull request merged**
